# Generated by Django 4.0.3 on 2022-10-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0002_alter_student_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
