# Generated by Django 4.0.3 on 2022-10-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0004_alter_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignChairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBEAPP.teacher')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBEAPP.department')),
            ],
        ),
    ]
