# Generated by Django 4.0.3 on 2022-10-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0006_assignexamcommittee'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonObeMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt1', models.IntegerField(default=0, null=True)),
                ('tt2', models.IntegerField(default=0, null=True)),
                ('tt3', models.IntegerField(default=0, null=True)),
                ('att', models.IntegerField(default=0, null=True)),
                ('sem', models.IntegerField(default=0, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBEAPP.assigncourse')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBEAPP.assignstudent')),
            ],
        ),
    ]
