# Generated by Django 4.0.3 on 2022-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0007_nonobemark'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigncourse',
            name='format',
            field=models.CharField(choices=[('OBE', 'OBE'), ('NonOBE', 'NonOBE')], max_length=200, null=True),
        ),
    ]
