# Generated by Django 4.0.3 on 2022-10-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0008_assigncourse_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonobemark',
            name='att',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nonobemark',
            name='sem',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nonobemark',
            name='tt1',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nonobemark',
            name='tt2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nonobemark',
            name='tt3',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
