# Generated by Django 4.0.3 on 2022-10-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0010_alter_nonobemark_att_alter_nonobemark_sem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObeMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt1', models.IntegerField(default=0, null=True)),
                ('tt2', models.IntegerField(default=0, null=True)),
                ('tt3', models.IntegerField(default=0, null=True)),
                ('att', models.IntegerField(default=0, null=True)),
                ('co1', models.IntegerField(default=0, null=True)),
                ('co2', models.IntegerField(default=0, null=True)),
                ('co3', models.IntegerField(default=0, null=True)),
                ('co4', models.IntegerField(default=0, null=True)),
                ('co5', models.IntegerField(default=0, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBEAPP.assigncourse')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OBEAPP.assignstudent')),
            ],
        ),
    ]
