# Generated by Django 4.0.3 on 2023-01-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0014_assigncourse_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonobemark',
            name='mark',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='mark',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20, null=True),
        ),
    ]
